# this is an example of the OncoBlocks API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: OncoBlocks API
  description: OncoBlocks Open Cancer Genomics API.
  version: "1.0.0"
# the domain of the service
host: api.oncoblocks.org
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
paths:
  /signal:
    get:
      summary: Get Discrete or Continuous Signal Data.
      description: Get Discrete or Continuous Signal Data, such as expression data, phosphoproteomic data or discretized copy number data.
      parameters:
        - name: stable_sample_id
          in: query
          description: Zero or more sample IDs.
          required: false
          type: array
          items:
            type: string
        - name: entrez_gene_id
          in: query
          description: Entrez Gene Ids.
          required: false
          type: array
          items:
            type: integer
        - name: stable_study_id
          in: query
          description: Zero or more sample IDs.
          required: false
          type: string
      responses:
        200:
          description: an array of signal objects.
          schema:
            title:  Signals
            type: array
            items:
              $ref: SignalData
definitions:
    SignalData:
      properties:
        stable_sample_id:
          type: integer
          format: int32
          description: Stable sample ID.
        gene_id:
          type: integer
          format: int32
          description: Entrez gene ID.
        gene_symbol:
          type: string
          description:  Official gene symbol.
        genome_coordinates:
          type:  string
          description:  Genomic coordinates.
        signal_value:
          type:  string
          description:  Signal intensity or annotation.